# Generated by Django 3.1.3 on 2020-11-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All_blogs',
            new_name='All_blog',
        ),
    ]
